/** Shared wording and arithmetic for evidence and live decisions. */
export const featureGuide=[
 ['Flow duration','seconds','Time from the beginning to the end of this measured bidirectional flow. Longer duration can mean a long connection, but does not by itself mean an attack.'],
 ['Forward packets','packets','Packets in the flow’s forward direction, from its originator toward its responder.'],
 ['Backward packets','packets','Packets travelling back from the responder toward the originator. Zero means none were counted in this direction.'],
 ['Flow packet rate','packets / second','How quickly packets occurred over the measured flow. Bursts and short durations can produce large rates. High rate alone is not a universal attack rule.'],
 ['Down/up ratio','ratio','Backward-to-forward packet ratio in the dataset’s flow representation. A value of 1 indicates equal directional packet counts. Preserve the collector’s zero-denominator convention.'],
 ['SYN flags','count','Packets carrying the TCP SYN flag, used in connection synchronization. It is a count, not a yes/no attack indicator.'],
 ['RST flags','count','Packets carrying the TCP RST flag, which resets a TCP connection. Resets can occur in both ordinary traffic and attacks.'],
 ['ACK flags','count','Packets carrying the TCP ACK flag, acknowledging received TCP data or connection state.'],
 ['Payload mean','bytes','Average packet payload size: the data portion measured by the flow collector, rather than a count of packets.'],
 ['Payload standard deviation','bytes','How much packet payload sizes vary around their mean. Zero indicates no variation among the measured payload sizes.'],
 ['Forward initial window','bytes','Initial advertised TCP receive-window size in the forward direction. Zero can occur in records without a measured TCP window; it does not prove an attack.'],
 ['Backward initial window','bytes','Initial advertised TCP receive-window size in the backward direction. Keep the measurement semantics consistent with the training data.']
];
export const modelGuide={
 'Logistic regression':'A static linear classifier in the transformed feature space. It does not learn during replay.',
 'Random forest':'A static ensemble of decision trees. It does not learn during replay.',
 static:'The initial neural network is frozen: no online weight updates.',
 ungoverned:'The neural network adapts when eligible, without calculating governance checks.',
 monitor_only:'The network adapts and records governance evidence. Failed checks are recorded but do not veto an update.',
 governed:'The network trains a candidate, then activates it only if every configured governance check passes.',
 no_replay:'Gated adaptation trained on recent records without the additional replay buffer.',
 no_attribution:'Gated adaptation with error-based triggers only; attribution change cannot trigger a candidate.'
};
export const metricGuide={
 attack_f1:['Attack F1','Combines attack precision and attack recall. 1 is best; 0 is worst. It is not overall accuracy or a calibrated probability.','2 × true positives / (2 × true positives + false positives + false negatives)'],
 balanced_accuracy:['Balanced accuracy','Average of attack recall and benign recall, giving both classes equal weight despite unequal counts.','(attack recall + benign recall) / 2'],
 attack_recall:['Attack recall','Fraction of actual attacks that the model flags. Missed attacks are false negatives.','correctly flagged attacks / all actual attacks'],
 benign_false_alarm_rate:['Benign false alarms','Fraction of actual benign flows incorrectly flagged as risky. Lower is better.','benign flows wrongly flagged / all benign flows'],
 attempts:['Candidate updates','Attempted model updates, including both accepted and rejected versions. This does not count blocked users or attack flows.','accepted candidate versions + rejected candidate versions']
};
export const pct=x=>(100*x).toFixed(2)+'%';
export const configGuide={
 batch_size:'Maximum flows in one prediction-before-feedback cycle. A 128-flow click contains four 32-flow cycles.',
 error_short:'Latest labelled prediction errors used for the recent error fraction.',
 error_long:'Total labelled errors required for an error trigger. The older reference uses 256 − 64 = 192 labels.',
 error_margin:'Required absolute rise in recent error fraction: 0.08 means 8 percentage points. The drift comparison is strictly greater than this margin.',
 attribution_threshold:'Maximum absolute change in normalized mean absolute feature contributions must exceed 0.15. This is a feature-importance shift, not a probability of drift.',
 min_update_gap:'Minimum processed flows between candidate training attempts, including rejected attempts.',
 adaptation_window:'Maximum recent labelled entries retained for candidate training. At least 64 recent labels and some current-batch labels are also required.',
 replay_size:'Maximum older labelled entries mixed into candidate training to retain previous behavior. This training buffer differs from the 1,280-flow Dataset replay tab.',
 update_epochs:'Number of sequential SGD passes over the recent-plus-replay candidate training set.',
 update_lr:'Learning rate: scale applied to each SGD gradient step. Weight regularization uses a fixed coefficient 0.0001.',
 eci_threshold:'Minimum Explanation Consistency Index for a passing check. ECI = (Jaccard + (Kendall tau + 1) / 2) / 2. Jaccard compares the top five features; tau compares all feature rankings.',
 max_anchor_loss_increase:'Largest permitted candidate-minus-old binary log-loss increase on identical fixed validation anchors. Lower loss is better; equality passes.',
 max_attack_miss_increase:'Largest permitted rise in missed-attack fraction on attack-labelled anchors. 0.05 means 5 percentage points; equality passes.'
};
export function decisionExplanation(r,config,mode){
 const pre=r.same_anchor_before,post=r.same_anchor_candidate,loss=post.loss-pre.loss,miss=post.attack_miss-pre.attack_miss;
 return {headline:r.accepted?(r.failed_checks.length?'New model activated despite flagged checks.':'New model activated; all configured checks passed.'):'Candidate model discarded; previous model kept.',
  meaning:`This decision concerns model version ${r.attempt}, trained after ${r.position} flows. It does not accept or reject a person, packet, or access request.`,
  trigger:r.trigger==='error_shift'?`Recent prediction error was ${pct(r.signals.short_error)} versus ${pct(r.signals.reference_error)} in the older reference window. The ${(100*(r.signals.short_error-r.signals.reference_error)).toFixed(2)} percentage-point rise exceeded the ${(100*config.error_margin).toFixed(0)}-point trigger margin.`:`The largest normalized attribution change was ${r.signals.attribution_shift.toFixed(4)}, compared with the ${config.attribution_threshold} trigger threshold. This means the importance pattern changed, not that an explanation was proven false.`,
  checks:[
   {name:'Explanation consistency',before:'Same fixed anchor inputs',after:r.explanation_consistency.eci.toFixed(4),limit:`ECI ≥ ${config.eci_threshold}`,pass:r.checks.explanation_consistency,why:`Top-five overlap (Jaccard) ${r.explanation_consistency.jaccard.toFixed(4)} and ranking agreement (Kendall tau) ${r.explanation_consistency.kendall_tau.toFixed(4)} combine into ECI. Similar explanations can still be wrong.`},
   {name:'Anchor prediction loss',before:pre.loss.toFixed(5),after:post.loss.toFixed(5),limit:`Increase ≤ ${config.max_anchor_loss_increase}`,pass:r.checks.anchor_loss,why:`Change ${loss>=0?'+':''}${loss.toFixed(5)}. Log loss penalizes inaccurate/confident predictions on the same validation reference records. Lower is better; this is not an error percentage.`},
   {name:'Missed attacks on anchors',before:pct(pre.attack_miss),after:pct(post.attack_miss),limit:`Increase ≤ ${100*config.max_attack_miss_increase} percentage points`,pass:r.checks.attack_miss,why:`Change ${miss>=0?'+':''}${(100*miss).toFixed(2)} percentage points among attack-labelled anchors. This does not assess every possible new attack.`},
   {name:'Update spacing',before:'Previous candidate attempt',after:'Checked at current stream position',limit:`At least ${config.min_update_gap} flows`,pass:r.checks.minimum_gap,why:'Prevents repeated candidate attempts too close together; one click does not force an update.'}
  ],policy:mode==='monitor_only'?'Audit-only records the checks and activates the candidate even when a check fails.':'Gated mode requires all four checks to pass; one failed check keeps the previous model.',
  fingerprint:r.accepted?'Active model hash equals candidate hash.':'Active model hash equals the before-update hash.'};
}
export function detectorExplanation(d,c){if(!d)return 'Process a replay or CSV batch to see the actual detector evidence here.';const s=d.signals??{},short=s.short??s.short_error??0,long=s.long??s.reference_error??0,shift=s.shift??s.attribution_shift??0;
 const error=d.error_history_labels>=c.error_long&&short>long+c.error_margin,attr=shift>c.attribution_threshold;
 const missing=[];if(!error&&!attr)missing.push('neither drift threshold crossed');if(d.flows_since_previous_attempt<c.min_update_gap)missing.push(`only ${d.flows_since_previous_attempt} flows since the last attempt (need ${c.min_update_gap})`);if(d.recent_labels<64)missing.push(`only ${d.recent_labels} recent labels (need 64)`);if(!d.current_labels)missing.push('this batch supplied no feedback labels');
 return `At flow ${d.position}, the last internal batch contained ${d.batch_size} flows and ${d.current_labels} labels. Error history: ${d.error_history_labels}/${c.error_long} labels. Recent error ${pct(short)}, reference ${pct(long)}; an error trigger needs a full history and an increase above ${100*c.error_margin} percentage points. Attribution change ${shift.toFixed(4)} versus ${c.attribution_threshold}. ${d.attempted?'A candidate was trained and checked. Error history then resets, including after a rejection.':'No candidate was trained: '+missing.join('; ')+'.'}`;
}
export const auditFieldGuide={schema_version:'Format of this record, not model quality.',engine_version:'Version name of the shared inference/update implementation.',attempt:'Number of the candidate training attempt in this session.',position:'Number of stream flows processed when this candidate was checked.',timestamp_utc:'Time recorded for the attempt; in the browser lab it uses this device’s clock.',trigger:'Which signal initiated the attempt; error shift takes precedence when both signals trigger.',signals:'Measured short/reference errors and maximum normalized attribution change.',training_record_ids:'Exact entries used for candidate learning; replay overlap can repeat IDs.',anchor_record_ids:'Fixed validation-record IDs used to compare both models.',model_before_sha256:'Fingerprint of the active weights before training the candidate.',candidate_sha256:'Fingerprint of the newly trained candidate weights.',active_model_sha256:'Fingerprint of the weights retained after the decision.',same_anchor_before:'Old model’s loss, attack misses and mean trust on fixed anchors.',same_anchor_candidate:'Candidate’s values on the identical anchors.',explanation_consistency:'ECI, top-five overlap, Kendall ranking agreement and ranked feature indices.',checks:'Pass/fail booleans for the configured research governance rules.',policy_mapping:'Research associations with ISO controls; not a certification.',mapping_scope:'Explicit limit on the policy mapping claim.',accepted:'Whether candidate weights became active, not whether a flow was permitted.',status:'ACCEPTED, ACCEPTED_WITH_FLAGS or REJECTED model update.',failed_checks:'Checks that failed, even if audit-only still accepted the update.',incremental_losses:'Training log loss reported for each of the three SGD passes; not held-out performance.',previous_record_sha256:'Link to the preceding record’s content fingerprint; null for the first.',record_sha256:'This record’s canonical-JSON SHA-256 fingerprint, excluding this field itself.',feedback_source:'Where labels came from; visitor assertions are not independently verified.',elapsed_ms:'Measured candidate-processing time on the executing device; not a controlled latency benchmark.'};

export const figureGuide=[
 ['01_dataset_audit','Dataset composition','Raw versus unique input vectors by family.','The family names identify dataset traffic categories. The horizontal count axis is logarithmic: equal spacing represents multiplication rather than equal additions. Paired bars compare raw rows with unique retained feature vectors after conflict exclusion. Deduplication drastically changes prevalence; these are record counts, not classifier performance.'],
 ['02_baselines_and_ablations','Baselines and ablations','Eight configurations, two protocols, five seeded splits.','The vertical axis is attack F1 from 0 to 1. Bars group model configurations under stationary and shifted replay. Each height is the mean of five runs; error bars are one sample standard deviation. Compare bars within the same protocol. Audit-only and ungoverned predictions are identical by design; logging alone does not improve classification.'],
 ['03_stream_performance','Performance through the stream','Primary-seed rolling balanced accuracy and error fraction.','The horizontal axis follows flow position in the constructed primary-seed stream. Values summarize nonoverlapping 256-flow reporting windows. Balanced accuracy treats both classes equally; error fraction counts all wrong classifications in that window. Dotted vertical boundaries mark deliberately constructed data regimes, not detected events or timestamps. The plot is not five-seed aggregate performance.'],
 ['04_roc_pr','ROC and precision–recall','Primary-seed comparisons across score thresholds.','ROC uses false-positive rate horizontally and attack true-positive rate vertically. Precision–recall uses attack recall horizontally and precision vertically. Curves vary the decision threshold; the normal deployed threshold is 0.5. The PR baseline is the observed attack prevalence. These diagnostics use primary-seed shifted predictions; high curve area does not prove probability calibration or every-family detection.'],
 ['05_confusion_matrices','Class-specific errors','Counts and within-true-class percentages.','Axes distinguish the true label from the predicted label: 0 benign, 1 attack. Diagonal cells are correct. A true attack predicted benign is a false negative; a true benign flow predicted attack is a false positive. Each percentage is normalized within its true class, not over the entire dataset. Colors visualize magnitudes and do not signify governance acceptance.'],
 ['06_governance_decisions','Accepted and rejected model candidates','ECI and anchor loss for actual primary-seed gated attempts.','Each point is one candidate model attempt, not a network user. ECI compares explanation rankings on fixed anchors. Anchor log-loss change compares candidate and old predictions on the same anchors. Dashed lines are the preselected policy limits. Green circles activate model versions; red crosses discard them. Passing ECI alone is insufficient when another check fails.'],
 ['07_per_family','Performance by traffic family','Correct classifications and actual held-out support.','Each category is a dataset family; support tells how many held-out examples contribute. The rate is correct classification within that family, not a separate calibrated probability. Tiny support can make rates unstable. Novel families were absent from initial fitting, but their labels may influence later prequential updates after their predictions.'],
 ['08_research_workflow','Experimental workflow','Preparation, disjoint split, model selection and evaluation.','Boxes name computational stages and arrows indicate data/control flow. Download and conflict/deduplication audit precede splitting. Training determines preprocessing and initial weights; validation selects checkpoints and anchors. Held-out streams are predicted before feedback-driven updates. Five seeds and two protocols lead to metrics and figures. Diagram arrows are workflow dependencies, not empirical causal evidence.'],
 ['09_live_architecture','GitHub Pages and browser execution architecture','Actual inference, candidate checks and local evidence storage.','Boxes identify the browser inputs, Web Worker running the shared model engine, fixed-anchor checks and local IndexedDB storage. Arrows trace predictions and candidate model updates. PASS / AUDIT-ONLY means a passing candidate is activated, or audit-only policy activates it despite flags. FAIL + GATED means the candidate weights are discarded and the previous active model remains. These branches govern model versions, not user access. GitHub Pages serves the files; your browser performs inference and learning. Local audit chains require a separately trusted saved head to establish evidence beyond browser-controlled consistency.']
];
