const $=id=>document.getElementById(id);
let meta,session=null,busy=false,stop=false,trace=[],latestAudit=null;
function message(text){$('error').textContent=text;$('error').hidden=!text}
async function api(path,body){
 const res=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin'});
 let data;try{data=await res.json()}catch{throw Error('The API did not return JSON. Open this lab on its deployed URL or run the local server.')}
 if(!res.ok){const e=Error(data.error||'Request failed');e.status=res.status;throw e}return data;
}
async function action(fn){if(busy)return;busy=true;message('');const buttons=[...document.querySelectorAll('button')].filter(b=>b.id!=='stopReplay');buttons.forEach(b=>b.disabled=true);try{await fn()}catch(e){message(e.message);if(e.status===409){try{update(await api('/api/session'))}catch{}}}finally{busy=false;buttons.forEach(b=>b.disabled=false)}}
function requireSession(){if(!session)throw Error('Start a lab session first.')}
function update(s){session={...session,...s};for(const k of ['seen','attempts','accepted','rejected'])$(k).textContent=session[k]??0;
 $('sessionMeta').textContent=(session.mode==='governed'?'Gated':'Audit-only')+' session · revision '+session.revision+' · '+(session.labeled??0)+' labels received';
 const n=session.replay_cursor??0,percent=100*n/(meta?.replay_size||1);$('replayFill').style.width=percent+'%';$('replayProgress').setAttribute('aria-valuenow',Math.round(percent));$('replayCount').textContent=n+' / '+(meta?.replay_size||0)+' held-out flows processed';
 const regime=(meta?.replay_boundaries||[]).filter(b=>n>=b).length;[...$('regimes').children].forEach((e,i)=>e.classList.toggle('active',i===regime));
}
function pipeline(candidate=false,flag=false,inferenceOnly=false){[...$('pipeline').children].forEach((e,i)=>{e.className=(i<(inferenceOnly?2:3)||candidate)?'done':'';if(flag&&i===4)e.className='flag'})}
function showScore(p,note){$('scoreValue').replaceChildren(document.createTextNode(((1-p)*100).toFixed(1)));const sm=document.createElement('small');sm.textContent='trust score / 100';$('scoreValue').append(sm);$('decision').textContent=p>=.5?'Flag network risk':'Lower network risk';$('decision').className='badge'+(p>=.5?' danger':'');$('scoreNote').textContent=note}
function showExplanations(items){const root=$('explanations');root.replaceChildren();const max=Math.max(...items.map(e=>Math.abs(e.contribution)),.001);for(const e of items.slice(0,6)){const row=document.createElement('div');row.className='explanation';const name=document.createElement('span');name.textContent=e.feature;const value=document.createElement('span');value.textContent=(e.contribution>=0?'+':'')+e.contribution.toFixed(4);const track=document.createElement('div');track.className='track';const fill=document.createElement('div');fill.className='fill';fill.style.width=100*Math.abs(e.contribution)/max+'%';fill.style.background=e.contribution>0?'#b7653c':'#117f80';track.append(fill);row.append(name,value,track);root.append(row)}}
function chart(){const svg=$('streamChart');svg.replaceChildren();const ns='http://www.w3.org/2000/svg';const line=(x1,y1,x2,y2,color,dash)=>{const e=document.createElementNS(ns,'line');for(const [k,v] of Object.entries({x1,y1,x2,y2,stroke:color,'stroke-dasharray':dash||''}))e.setAttribute(k,v);svg.append(e)};
 for(const [v,label] of [[0,'100'],[.5,'50'],[1,'0']]){line(34,12+v*140,590,12+v*140,'#d7e2e8',v===.5?'4 4':'');const t=document.createElementNS(ns,'text');t.setAttribute('x',0);t.setAttribute('y',16+v*140);t.setAttribute('fill','#627681');t.setAttribute('font-size','11');t.textContent=label;svg.append(t)}
 const a=trace.slice(-512);if(a.length){const p=document.createElementNS(ns,'polyline');p.setAttribute('points',a.map((r,i)=>(34+i/Math.max(1,a.length-1)*556)+','+(12+r.attack_probability*140)).join(' '));p.setAttribute('fill','none');p.setAttribute('stroke','#117f80');p.setAttribute('stroke-width','1.4');svg.append(p)}
 $('streamNote').textContent=a.length?'Actual trust scores · positions '+a[0].position+'–'+a.at(-1).position+' · dashed line = score 50':'Stream chart appears after replay or CSV processing.';
}
function consume(r){update(r);trace.push(...r.predictions);trace=trace.slice(-512);chart();$('explanations').textContent='Single-flow contributions are separate from stream updates. Run inference to inspect the current model.';const last=r.predictions.at(-1);if(last)showScore(last.attack_probability,'Last streamed flow · '+last.family+' · source '+last.source_row);pipeline(!!r.events.length,r.events.some(e=>e.failed_checks.length));if(r.events.length)$('modelFingerprint').textContent='Active model SHA-256: '+r.events.at(-1).active_model_sha256;}
async function audits(){requireSession();latestAudit=await api('/api/audit');const records=latestAudit.records,root=$('auditRecords');root.replaceChildren();$('auditState').textContent=records.length?records.length+' actual candidate records · chain head '+latestAudit.chain_head:'No candidates yet. Drift detection requires enough observed evidence; updates are not forced.';
 for(const r of [...records].reverse()){const d=document.createElement('details');d.className='audit-record';const summary=document.createElement('summary');summary.textContent='#'+r.attempt+' · flow '+r.position+' · '+r.status+' · ECI '+r.explanation_consistency.eci.toFixed(3)+' · '+r.trigger;const p=document.createElement('p');p.textContent=r.failed_checks.length?'Flagged checks: '+r.failed_checks.join(', '):'All configured checks passed.';const pre=document.createElement('pre');pre.textContent=JSON.stringify(r,null,2);d.append(summary,p,pre);root.append(d)}
}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('newSession').addEventListener('click',()=>action(async()=>{stop=true;update(await api('/api/session',{mode:$('mode').value}));trace=[];chart();$('scoreValue').textContent='—';$('scoreNote').textContent='Submit a measured flow to see the new session model.';$('explanations').replaceChildren();[...$('pipeline').children].forEach(e=>e.className='');$('modelFingerprint').textContent='Session reset to the published model.';$('decision').textContent='Ready for inference';$('decision').className='badge';await audits()}));
const labels=['Flow duration','Forward packets','Backward packets','Flow packet rate','Down/up ratio','SYN flags','RST flags','ACK flags','Payload mean','Payload standard deviation','Forward initial window','Backward initial window'];
const units=['seconds','packets','packets','packets / second','ratio','count','count','count','bytes','bytes','bytes','bytes'];
function choose(){const row=meta.examples[Number($('example').value)];row.x.forEach((v,i)=>$('f'+i).value=v);$('exampleNote').textContent='Dataset row '+row.id+' · '+row.family+' · actual label: '+(row.y?'attack':'benign')+'. This label is not passed into inference.'}
$('example').addEventListener('change',choose);
$('flowForm').addEventListener('submit',e=>{e.preventDefault();action(async()=>{requireSession();const x=meta.features.map((_,i)=>Number($('f'+i).value));const r=await api('/api/infer',{x});showScore(r.attack_probability,'Raw model score, not a calibrated guarantee. '+(r.outside_training_range.length?'Outside training range: '+r.outside_training_range.join(', '):'Input is within the training feature ranges.'));showExplanations(r.explanation);$('modelFingerprint').textContent='Active model SHA-256: '+r.model_sha256;pipeline(false,false,true)})});
async function replayOne(){requireSession();const r=await api('/api/replay',{revision:session.revision,request_id:crypto.randomUUID(),count:128});consume(r);if(r.events.length)await audits();}
$('replayBatch').addEventListener('click',()=>action(replayOne));
$('replayAll').addEventListener('click',()=>action(async()=>{requireSession();stop=false;$('stopReplay').disabled=false;try{while(!stop&&session.replay_cursor<meta.replay_size){await replayOne();await new Promise(r=>setTimeout(r,120))}await audits()}finally{$('stopReplay').disabled=true}}));
$('stopReplay').addEventListener('click',()=>{stop=true;$('stopReplay').disabled=true});
$('refreshAudit').addEventListener('click',()=>action(audits));
$('exportAudit').addEventListener('click',()=>action(async()=>{await audits();download('drifttrust-session-audit.json',JSON.stringify(latestAudit,null,2))}));
function parseCSV(text){const rows=[];let row=[],field='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){field+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.trim()))rows.push(row);row=[];field=''}else field+=c}if(quote)throw Error('CSV contains an unclosed quote.');row.push(field);if(row.some(x=>x.trim()))rows.push(row);return rows}
$('template').addEventListener('click',()=>{if(!meta)return;const r=meta.examples[0];download('flow-example.csv',meta.features.concat('label').join(',')+'\n'+r.x.concat(r.y).join(',')+'\n','text/csv')});
$('submitCSV').addEventListener('click',()=>action(async()=>{requireSession();const file=$('csvFile').files[0];if(!file)throw Error('Select a CSV file.');if(file.size>2*1024*1024)throw Error('CSV must be at most 2 MB.');const grid=parseCSV(await file.text());if(grid.length<2||grid.length>257)throw Error('CSV must contain 1–256 records plus a header.');const head=grid.shift().map(x=>x.trim().replace(/^\uFEFF/,''));if(new Set(head).size!==head.length)throw Error('Duplicate column names are not allowed.');const columns=meta.features.map(f=>head.indexOf(f));if(columns.includes(-1))throw Error('Missing columns: '+meta.features.filter((_,i)=>columns[i]<0).join(', '));const li=head.indexOf('label');const rows=grid.map((r,i)=>{if(r.length!==head.length)throw Error('Column count mismatch on data row '+(i+1));const x=columns.map(j=>{if(!r[j].trim())throw Error('Missing numeric value on data row '+(i+1));const n=Number(r[j]);if(!Number.isFinite(n)||n<0)throw Error('Invalid non-negative numeric value on data row '+(i+1));return n});const raw=li>=0?r[li].trim():'';if(!['','0','1'].includes(raw))throw Error('Label must be blank, 0 or 1 on row '+(i+1));return {x,y:raw===''?null:Number(raw)}});const r=await api('/api/stream',{revision:session.revision,request_id:crypto.randomUUID(),rows});consume(r);await audits()}));
for(const button of document.querySelectorAll('[role=tab]'))button.addEventListener('click',()=>{document.querySelectorAll('[role=tab]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!==button.getAttribute('aria-controls'))});
try{
 const health=await api('/api/health');meta=await api('/api/model');$('serviceDot').classList.add('online');$('serviceText').textContent='Model online · database connected';$('example').replaceChildren();
 for(const [i,r] of meta.examples.entries()){const option=document.createElement('option');option.value=i;option.textContent=r.family+' · row '+r.id;$('example').append(option)}
 for(const [i,f] of meta.features.entries()){const label=document.createElement('label');label.textContent=labels[i];const input=document.createElement('input');input.id='f'+i;input.type='number';input.min='0';input.max='1000000000000000';input.step='any';input.required=true;const small=document.createElement('small');small.textContent=units[i]+' · '+f;label.append(input,small);$('fields').append(label)}
 $('csvSchema').textContent=meta.features.concat('label (optional)').join('\n');choose();chart();
 try{update(await api('/api/session'));$('mode').value=session.mode;await audits()}catch(e){if(e.status!==401)throw e}
}catch(e){$('serviceText').textContent='Service unavailable';message(e.message)}
