import {api} from './runtime/browser-client.mjs';
import {digest} from './runtime/engine.mjs';
import {featureGuide,decisionExplanation,detectorExplanation,auditFieldGuide,configGuide,pct} from './explanations.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let meta,session=null,busy=false,stop=false,trace=[],latestAudit=null;
function message(text){$('error').textContent=text;$('error').hidden=!text}
function buttons(){for(const b of document.querySelectorAll('button'))if(!b.hasAttribute('data-stage'))b.disabled=busy&&b.id!=='stopReplay';$('stopReplay').disabled=!busy||stop;if(!busy&&session?.replay_cursor>=meta?.replay_size){$('replayBatch').disabled=true;$('replayAll').disabled=true}}
async function action(fn){if(busy)return;busy=true;message('');buttons();try{await fn()}catch(e){message(e.message);if(e.status===409){try{restore(await api('/api/session'))}catch{}}}finally{busy=false;stop=true;buttons()}}
function requireSession(){if(!session)throw Error('Start a model session first. This loads the initial weights and chooses the update policy.')}
function policyHelp(){const selected=$('mode').value,description=selected==='governed'?'Gated: train a candidate copy, then discard it if any configured check fails.':'Audit-only: train and activate candidates, while recording checks that failed.';$('policyHelp').textContent=description+(session&&selected!==session.mode?' This is only the NEXT session’s policy; click Start/reset to apply it. Your current policy has not changed.':' Start/reset applies this choice from the initial published model.')} $('mode').onchange=policyHelp;
function update(s){session={...session,...s};for(const k of ['seen','attempts','accepted','rejected'])$(k).textContent=session[k]??0;
 $('sessionMeta').textContent=(session.mode==='governed'?'Gated':'Audit-only')+' active · revision '+session.revision+' · '+session.labeled+' labels received';
 $('counterMeaning').textContent=`${session.seen} stream flows have been scored. The engine trained ${session.attempts} proposed model versions: ${session.accepted} activated + ${session.rejected} discarded = ${session.attempts} attempts. These are model decisions, not accepted/rejected users. ${session.labeled} flows supplied feedback labels.`;
 const n=session.replay_cursor??0,total=meta?.replay_size||1280;$('replayFill').style.width=100*n/total+'%';$('replayProgress').setAttribute('aria-valuenow',n);$('replayProgress').setAttribute('aria-valuemax',total);$('replayCount').textContent=`${n} / ${total} held-out replay flows processed (${(100*n/total).toFixed(1)}%).`;
 const regime=Math.min(3,Math.floor(Math.max(0,n-1)/320));[...$('regimes').children].forEach((e,i)=>e.classList.toggle('active',i===regime));$('regimeHelp').textContent=n>=total?'Replay complete. The final phase returned to novel families. Start/reset to compare from identical initial weights.':`Four phases of 320 flows: known, novel, known return, novel return. ${n?`Last processed flow belongs to phase ${regime+1}.`:'No flows processed yet.'} Highlighting describes the data mix, not detected drift ground truth.`;
 if(s.active_model_sha256)$('modelFingerprint').textContent=s.active_model_sha256;
 if(s.last_diagnostics)$('detectorMeaning').textContent=detectorExplanation(s.last_diagnostics,meta.config);policyHelp();buttons();
}
function pipeline(candidate=false,flag=false,inferenceOnly=false){[...$('pipeline').children].forEach((e,i)=>{e.className='secondary '+((i<(inferenceOnly?2:3)||candidate)?'done':'');if(flag&&i===4)e.className='secondary flag'})}
function showScore(p,note,label=null){$('scoreValue').replaceChildren(document.createTextNode(((1-p)*100).toFixed(1)));const sm=document.createElement('small');sm.textContent='trust score / 100';$('scoreValue').append(sm);$('decision').textContent=p>=.5?'Flag network risk':'Lower network risk';$('decision').className='badge'+(p>=.5?' danger':'');$('scoreNote').textContent=note;
 const truth=label===0||label===1?` Compared with the supplied label (${label?'attack':'benign'}), this is ${Number(p>=.5)===label?'a correct classification':label?'a missed attack (false negative)':'a false alarm (false positive)'}.`:' No valid ground-truth label is available for this input, so correctness is unknown.';
 $('scoreMeaning').textContent=`Attack score = ${p.toFixed(6)}. Trust = 100 × (1 − ${p.toFixed(6)}) = ${(100*(1-p)).toFixed(1)} / 100. The ${p>=.5?'attack score is at least 0.5, so the model flags':'attack score is below 0.5, so the model does not flag'} network risk.${truth} This score does not authorize access or guarantee safety.`;
}
function showExplanations(items){const root=$('explanations');root.replaceChildren();const max=Math.max(...items.map(e=>Math.abs(e.contribution)),.001);for(const e of items){const row=document.createElement('details');row.className='explanation-detail';const name=featureGuide[meta.features.indexOf(e.feature)][0];const summary=document.createElement('summary');summary.textContent=name+' · '+(e.contribution>=0?'+':'')+e.contribution.toFixed(5);const track=document.createElement('div');track.className='track';const fill=document.createElement('div');fill.className='fill';fill.style.width=100*Math.abs(e.contribution)/max+'%';fill.style.background=e.contribution>0?'#b7653c':'#117f80';track.append(fill);const p=document.createElement('p');p.textContent=`${e.feature}: the observed value ${e.contribution>=0?'raises':'lowers'} the attack score by ${Math.abs(e.contribution).toFixed(5)} relative to setting its transformed value to zero (the training mean in log space). This is a model sensitivity comparison, not a causal explanation. The bar is scaled relative to the largest contribution in this input.`;row.append(summary,track,p);root.append(row)}}
function point(){const r=trace[Number($('pointPicker').value)];$('pointMeaning').textContent=r?`Flow position ${r.position}; source ${r.source_row}; family ${r.family}; attack score ${r.attack_probability.toFixed(6)}; trust ${(100*(1-r.attack_probability)).toFixed(1)}. ${r.label===null?'No label; correctness cannot be checked.':`Label ${r.label} (${r.label?'attack':'benign'}). ${Number(r.attack_probability>=.5)===r.label?'Correct classification.':r.label?'Missed attack (false negative).':'False alarm on benign traffic.'}`} This point was scored before that batch’s labels influenced learning.`:'No stream point is available yet.'} $('pointPicker').oninput=point;
function chart(){const svg=$('streamChart');svg.replaceChildren();const ns='http://www.w3.org/2000/svg',add=(tag,attrs,text)=>{const e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;svg.append(e);return e};
 for(const [p,label]of [[0,'100'],[.5,'50'],[1,'0']]){add('line',{x1:38,y1:15+p*140,x2:588,y2:15+p*140,stroke:'#ccdadd','stroke-dasharray':p===.5?'5 4':''});add('text',{x:0,y:20+p*140,fill:'#425c69','font-size':12},label)}
 const a=trace.slice(-512);if(a.length){add('polyline',{points:a.map((r,i)=>(38+i/Math.max(1,a.length-1)*550)+','+(15+r.attack_probability*140)).join(' '),fill:'none',stroke:'#117f80','stroke-width':1.4});add('text',{x:38,y:181,'font-size':12,fill:'#425c69'},String(a[0].position));add('text',{x:588,y:181,'text-anchor':'end','font-size':12,fill:'#425c69'},String(a.at(-1).position))}add('text',{x:300,y:204,'text-anchor':'middle','font-size':12,fill:'#425c69'},'Processed flow position');
 $('streamNote').textContent=a.length?`Showing ${a.length} real predictions at positions ${a[0].position}–${a.at(-1).position}. Reload restores these saved stream values.`:'No stream chart yet. Single-flow scoring has no stream position.';$('pointPicker').max=Math.max(0,a.length-1);$('pointPicker').value=Math.max(0,a.length-1);$('pointPicker').disabled=!a.length;point();
}
function consume(r){update(r);trace=r.trace??[...trace,...r.predictions].slice(-512);chart();$('explanations').textContent='Stream updates have their own anchor explanations in the audit below. Run Single flow to inspect contributions under the current model.';const last=r.predictions.at(-1);if(last)showScore(last.attack_probability,`Last streamed flow · ${last.family} · source ${last.source_row}`,last.label);pipeline(!!r.events.length,r.events.some(e=>e.failed_checks.length));$('detectorMeaning').textContent=detectorExplanation(r.diagnostics.at(-1),meta.config)}
function restore(s){update(s);trace=s.trace??[];chart();const last=trace.at(-1);if(last)showScore(last.attack_probability,`Restored last streamed prediction · ${last.family} · source ${last.source_row}`,last.label);$('detectorMeaning').textContent=detectorExplanation(s.last_diagnostics,meta.config)}
function renderAudit(){if(!latestAudit)return;const all=latestAudit.records,filter=$('auditFilter').value,records=all.filter(r=>filter==='all'||(filter==='accepted'?r.accepted:!r.accepted));$('auditRecords').replaceChildren();$('auditState').textContent=`${all.length} saved candidate model attempts; ${records.length} shown. Each row is a trained model version, not a flow access decision. ${all.length?'Expand a row for the precise acceptance/rejection reason.':'Run replay or supply enough labelled evidence to make an attempt possible.'}`;$('chainHead').textContent=latestAudit.chain_head??'No candidate record yet, so no chain head.';
 for(const r of [...records].reverse()){const x=decisionExplanation(r,meta.config,session.mode),d=document.createElement('details');d.className='audit-record';d.innerHTML=`<summary>Model candidate #${r.attempt} · after flow ${r.position} · ${r.accepted?(r.failed_checks.length?'ACTIVATED WITH FLAGS':'ACTIVATED'):'DISCARDED'} · ECI ${r.explanation_consistency.eci.toFixed(3)}</summary><h3>${esc(x.headline)}</h3><p>${esc(x.meaning)}</p><p><b>Why training was attempted:</b> ${esc(x.trigger)}</p><p>${esc(x.policy)}</p><div class="table-wrap"><table class="check-table"><caption>Old and candidate models compared on the identical fixed validation anchors</caption><thead><tr><th>Check</th><th>Before</th><th>Candidate</th><th>Rule</th><th>Outcome and meaning</th></tr></thead><tbody>${x.checks.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.before)}</td><td>${esc(c.after)}</td><td>${esc(c.limit)}</td><td><b class="${c.pass?'pass':'fail'}">${c.pass?'PASS':'FAIL'}</b> ${esc(c.why)}</td></tr>`).join('')}</tbody></table></div><p><b>Model identity:</b> ${esc(x.fingerprint)}</p><details><summary>What does every raw audit field mean?</summary><dl class="field-dictionary">${Object.entries(r).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(auditFieldGuide[k]??'Additional versioned audit metadata.')} ${Array.isArray(v)?`This record has ${v.length} entries.`:''}</dd>`).join('')}</dl><p>In explanation_consistency, top_before/top_after contain zero-based feature indices: ${meta.features.map((f,i)=>i+' = '+f).map(esc).join('; ')}. In same_anchor values, mean_trust is the average 1 − attack score across anchors, not validation accuracy.</p></details><details><summary>Raw JSON evidence for independent inspection</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details>`;$('auditRecords').append(d)}
} $('auditFilter').onchange=renderAudit;
async function audits(){requireSession();latestAudit=await api('/api/audit');renderAudit()}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('newSession').onclick=()=>action(async()=>{stop=true;update(await api('/api/session',{mode:$('mode').value}));trace=[];chart();$('scoreValue').textContent='—';$('scoreNote').textContent='Initial model loaded. Run inference or process a stream.';$('decision').textContent='Ready for inference';$('decision').className='badge';$('scoreMeaning').textContent='No new score yet. Trust is 100 × (1 − attack score). Reset affected the model session, not the example fields.';$('explanations').textContent='Run single-flow inference to see all 12 feature comparisons.';$('detectorMeaning').textContent='No stream evidence in this new session.';$('verifyState').textContent='';[...$('pipeline').children].forEach(e=>e.className='secondary');await audits()});
function edited(){const e=meta.examples[Number($('example').value)],changed=meta.features.some((_,i)=>Number($('f'+i).value)!==e.x[i]);$('exampleNote').textContent=`Source row ${e.id}; family ${e.family}; original known label ${e.y} (${e.y?'attack':'benign'}). `+(changed?'EDITED INPUT: original label does not establish correctness for your changes.':'This exact example is held out from initial training. Its label is shown for comparison, not sent into inference.');return changed}
function featureValue(i){const input=$('f'+i),n=Number(input.value),guide=featureGuide[i],bounds=meta.bounds[i];$('fv'+i).textContent=input.value===''?'Enter a measured number.':`Current value: ${n} ${guide[1]}. ${n<bounds.min||n>bounds.max?'Outside the initial training range.':'Within the initial training range.'} Observed training minimum ${bounds.min}, maximum ${bounds.max}. Range membership does not guarantee a correct prediction.`}
function choose(){const e=meta.examples[Number($('example').value)];e.x.forEach((v,i)=>{$('f'+i).value=v;featureValue(i)});edited()} $('example').onchange=choose;
$('flowForm').onsubmit=e=>{e.preventDefault();action(async()=>{requireSession();const x=meta.features.map((_,i)=>Number($('f'+i).value)),changed=edited(),sample=meta.examples[Number($('example').value)],r=await api('/api/infer',{x});showScore(r.attack_probability,r.outside_training_range.length?'Outside initial training range: '+r.outside_training_range.join(', '):'Within initial training feature ranges; correctness still requires ground truth.',changed?null:sample.y);showExplanations(r.explanation);$('modelFingerprint').textContent=r.model_sha256;pipeline(false,false,true);$('stageHelp').textContent='Only Input and Predict ran. No feedback, candidate training or adaptation record was produced by this single-flow operation.'})};
async function replayOne(){requireSession();const r=await api('/api/replay',{revision:session.revision,request_id:crypto.randomUUID(),count:128});consume(r);if(r.events.length)await audits()}
$('replayBatch').onclick=()=>action(replayOne);$('replayAll').onclick=()=>action(async()=>{requireSession();stop=false;buttons();try{while(!stop&&session.replay_cursor<meta.replay_size)await replayOne();await audits()}finally{stop=true}});$('stopReplay').onclick=()=>{stop=true;$('stopReplay').disabled=true};
$('refreshAudit').onclick=()=>action(audits);$('exportAudit').onclick=()=>action(async()=>{await audits();download('drifttrust-session-audit.json',JSON.stringify(latestAudit,null,2))});
$('verifyAudit').onclick=()=>action(async()=>{await audits();let head=null;for(const record of latestAudit.records){const {record_sha256,...rest}=record;if(await digest(rest)!==record_sha256||rest.previous_record_sha256!==head)throw Error('Audit chain verification failed: content or links differ.');head=record_sha256}if(head!==latestAudit.chain_head)throw Error('Audit head does not match.');$('verifyState').textContent=`Verified ${latestAudit.records.length} record content hashes and their links. This proves internal consistency against this saved head, not label truth or independent immutability.`});
export function parseCSV(text){const rows=[];let row=[],field='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){field+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.trim()))rows.push(row);row=[];field=''}else field+=c}if(quote)throw Error('CSV contains an unclosed quote.');row.push(field);if(row.some(x=>x.trim()))rows.push(row);return rows}
$('csvFile').onchange=()=>{const f=$('csvFile').files[0];$('csvNote').textContent=f?`${f.name} · ${(f.size/1024).toFixed(1)} KB selected. Click Process CSV stream to validate and calculate locally.`:'No CSV selected.'};
$('template').onclick=()=>{if(!meta)return;const r=meta.examples[0];download('flow-example.csv',meta.features.concat('label').join(',')+'\n'+r.x.concat(r.y).join(',')+'\n','text/csv')};
$('submitCSV').onclick=()=>action(async()=>{requireSession();const file=$('csvFile').files[0];if(!file)throw Error('Choose a CSV file first.');if(file.size>2*1024*1024)throw Error('CSV must be at most 2 MB.');const grid=parseCSV(await file.text());if(grid.length<2||grid.length>257)throw Error('CSV needs 1–256 records and a header.');const head=grid.shift().map(x=>x.trim().replace(/^\uFEFF/,''));if(new Set(head).size!==head.length)throw Error('Duplicate CSV column names.');const columns=meta.features.map(f=>head.indexOf(f));if(columns.includes(-1))throw Error('Missing columns: '+meta.features.filter((_,i)=>columns[i]<0).join(', '));const li=head.indexOf('label'),rows=grid.map((r,i)=>{if(r.length!==head.length)throw Error('Column count mismatch at data row '+(i+1));const x=columns.map(j=>{const v=Number(r[j]);if(!r[j].trim()||!Number.isFinite(v)||v<0)throw Error('Invalid measurement at data row '+(i+1));return v});const y=li<0?'':r[li].trim();if(!['','0','1'].includes(y))throw Error('Use blank, 0 or 1 for label at row '+(i+1));return {x,y:y===''?null:Number(y)}});consume(await api('/api/stream',{revision:session.revision,request_id:crypto.randomUUID(),rows}));await audits()});
const tabTexts={single:'Single flow reads the current model, returns one score and explains its features. No training.',replay:'Replay feeds held-out measured traffic and labels through the real update engine. Updates require sufficient evidence.',upload:'CSV processes your compatible measurements locally. Labels enable supervised feedback; blank labels do not.'};
for(const button of document.querySelectorAll('[role=tab]'))button.onclick=()=>{document.querySelectorAll('[role=tab]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!==button.getAttribute('aria-controls'));$('tabHelp').textContent=tabTexts[button.getAttribute('aria-controls')]};
const stages=['Input: lab.mjs reads numeric values or parses CSV; browser-worker.mjs validates every row with transform().','Predict: engine.mjs applies log1p, training normalization, clipping, the 12–24–1 MLP and sigmoid. All 32 current-batch scores precede label feedback.','Detect: processBatch compares recent versus older labelled errors and normalized attribution patterns. It also checks labels and update spacing.','Candidate: fit() trains a copy of the active weights on recent and replay entries using three SGD passes. That copy is not active yet.','Audit: fixed-anchor metrics and ECI are checked. Policy chooses candidate or old weights, and a hash-linked AJR records the evidence.'];document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{$('stageHelp').textContent=stages[Number(b.dataset.stage)]});
const paths={infer:[['lab.mjs','browser-client.mjs','browser-worker.mjs','engine: transform → predict → explain','render score'],stages[1]+' No HTTP /api request or model mutation occurs.'],replay:[['CSV / replay rows','Web Worker','processBatch: predict → feedback','fit candidate → anchor checks','IndexedDB state + AJR'],stages[2]+' '+stages[3]+' '+stages[4]],audit:[['Refresh / Export / Verify','read IndexedDB audit','canonical JSON → SHA-256','check previous hash and chain head'], 'These operations read or verify saved evidence. They do not retrain or reverse previous decisions.'],train:[['research/prepare.py','trained model + held-out splits','research/run.mjs + engine.mjs','research/report.py','metrics and nine figures'],'This offline Python/Node path creates the published experiments. Initial fitting uses training data; validation selects checkpoints and anchors; test flows are predicted before their labels enter online updates.']};
function codeFlow(){const [p,t]=paths[$('flowAction').value];$('codePath').innerHTML=p.map(x=>'<span>'+esc(x)+'</span>').join('<b aria-hidden="true">→</b>');$('codeMeaning').textContent=t} $('flowAction').onchange=codeFlow;codeFlow();
const familyNames={'ARP_poisioning':'Dataset spelling of ARP poisoning: traffic labelled as an attack involving manipulated address-resolution mappings. Held out from initial training.','DDOS_Slowloris':'Slowloris-family testbed attack traffic; held out from initial training.','NMAP_XMAS_TREE_SCAN':'Nmap Xmas scan traffic; held out from initial training.','MQTT_Publish':'Benign labelled MQTT device-publish traffic.','Thing_Speak':'Benign labelled ThingSpeak device-service traffic.','Wipro_bulb':'Benign labelled smart-bulb traffic.','DOS_SYN_Hping':'Testbed SYN-flood attack family generated with hping.','Metasploit_Brute_Force_SSH':'Testbed SSH brute-force attack family.','NMAP_UDP_SCAN':'UDP scanning traffic.','NMAP_OS_DETECTION':'Operating-system detection scan traffic.','NMAP_TCP_scan':'TCP scanning traffic.','NMAP_FIN_SCAN':'FIN scanning traffic.'};
try{await api('/api/health');meta=await api('/api/model');$('serviceDot').classList.add('online');$('serviceText').textContent='Real model ready · local browser storage connected';$('example').replaceChildren();for(const [i,r]of meta.examples.entries()){const option=document.createElement('option');option.value=i;option.textContent=r.family+' · row '+r.id;$('example').append(option)}
 for(const [i,f]of meta.features.entries()){const cell=document.createElement('div');cell.className='feature-cell';cell.innerHTML=`<label for="f${i}">${esc(featureGuide[i][0])}<input id="f${i}" type="number" min="0" max="1000000000000000" step="any" required aria-describedby="fv${i}"></label><small>${esc(featureGuide[i][1])} · ${esc(f)}</small><details><summary>Meaning and current value</summary><p>${esc(featureGuide[i][2])}</p><p id="fv${i}" class="caption"></p></details>`;$('fields').append(cell);$('f'+i).oninput=()=>{featureValue(i);edited()}}
 $('csvSchema').textContent=meta.features.map((f,i)=>f+' — '+featureGuide[i][1]).concat('label — optional: 0 benign, 1 attack, blank unknown').join('\n');$('familyGuide').innerHTML=Object.entries(familyNames).map(([k,v])=>`<p><b>${esc(k)}</b>: ${esc(v)}</p>`).join('');$('technicalGlossary').innerHTML=Object.entries({MLP:'Multilayer perceptron: the trained neural network mapping 12 flow features to an attack score.',SGD:'Stochastic gradient descent: small weight adjustments using prediction error and labelled entries.',ECI:'Explanation Consistency Index: similarity of important-feature rankings before and after a candidate update on fixed anchors.',Anchor:'A fixed validation example used for a like-for-like model comparison. Anchors do not cover all novel attacks.',Replay:'A bounded buffer of older labelled entries mixed with recent entries for training. This differs from the Dataset replay input tab.',AJR:'Adaptation Justification Record: evidence for one candidate model attempt.',SHA256:'Content fingerprint used to identify weights or record content.',IndexedDB:'A database in this browser profile. Clearing site data removes these local sessions.'}).map(([k,v])=>`<p><b>${k}</b>: ${v}</p>`).join('');$('technicalGlossary').insertAdjacentHTML('beforeend','<h3>Every configured model setting</h3><dl class="field-dictionary">'+Object.entries(meta.config).map(([k,v])=>'<dt>'+esc(k)+' = '+esc(v)+'</dt><dd>'+esc(configGuide[k]??'Versioned model configuration.')+'</dd>').join('')+'</dl><p>The initial neural network has 12 inputs, 24 tanh hidden units and one sigmoid attack-score output. Inputs use log1p, training mean/standard deviation, then clipping to [−8, 8]. Both models are compared on 96 fixed validation anchors.</p>');$('example').value=Math.max(0,meta.examples.findIndex(r=>r.family==='MQTT_Publish'));choose();$('tabHelp').textContent=tabTexts.single;chart();policyHelp();try{restore(await api('/api/session'));$('mode').value=session.mode;policyHelp();await audits()}catch(e){if(e.status!==401)throw e;$('auditState').textContent='No active session. Start one, then process labelled evidence to see candidate records.'}
}catch(e){$('serviceText').textContent='Model unavailable';message(e.message)}
