import {parameterStep} from './runtime/math-trace.mjs';
import {decisionExplanation,featureGuide} from './explanations.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>typeof x!=='number'?'—':x!==0&&(Math.abs(x)<.0001||Math.abs(x)>999999)?x.toExponential(5):x.toFixed(6);
const box=(label,value,extra='')=>`<div class="math-box ${extra}"><span>${label}</span><output title="${esc(value)}" data-value="${esc(value)}">${fmt(value)}</output></div>`;
const stages=['Prepare inputs','Hidden neuron','Attack score','Trust score','Learn a candidate','Compare models','Policy decision'];

export class MathTheatre {
 constructor(root){
  this.root=root;this.items=[];this.current=null;this.stage=0;this.neuron=0;this.feature=0;this.variant='before';this.timer=null;this.meta=null;
  root.innerHTML=`<div class="math-top"><div><p class="math-kicker">INSIDE DRIFTTRUST · 12 → 24 → 1</p><h2>A prediction you can follow.</h2><p>Explore the network. Open its equations. Watch a proposed model meet the gate.</p></div><div class="math-launch"><button id="mathRun" disabled>Animate selected flow ↗</button><a class="math-input-link" href="#single">Choose a flow below ↓</a></div></div>
   <div class="math-toolbar"><label class="math-history">Captured calculation<select id="mathHistory" disabled><option>No calculation captured yet</option></select></label><div class="math-playback"><button id="mathReplay" aria-label="Replay calculation from the beginning" disabled>↺ Replay</button><button id="mathPrevious" aria-label="Previous calculation step" disabled>←</button><button id="mathPlay" disabled>▶ Play</button><button id="mathNext" aria-label="Next calculation step" disabled>→</button></div><label>Speed<select id="mathSpeed"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></label><label class="math-motion"><input id="mathReduced" type="checkbox"> Reduced motion</label></div>
   <p id="mathCapture" class="math-caption">Start a session, then run Single flow or Dataset replay. Each animation uses an actual captured calculation.</p>
   <div class="math-scene-scroll" tabindex="0" role="region" aria-label="Interactive neural network; scroll horizontally on narrow screens"><svg id="mathNetwork" role="group" viewBox="0 0 1120 420" aria-label="Twelve inputs, twenty-four hidden neurons, one sigmoid output"></svg></div>
   <div class="math-legend"><span><i class="positive"></i> Positive value</span><span><i class="negative"></i> Negative value</span><span>Node brightness = activation magnitude</span><span>Selected connections reveal their weights</span></div>
   <div id="mathStages" class="math-stages"></div><label class="math-scrub">Calculation step<input id="mathScrub" type="range" min="0" max="3" value="0" disabled></label>
   <div class="math-narration" aria-live="polite"><span id="mathStepNumber">READY</span><h3 id="mathStepTitle">Your measurements become the next calculation.</h3><p id="mathNarration">The same trained network powers the lab and this view. No illustrative weights are substituted.</p></div>
   <div class="math-inspect-controls"><label>Input to inspect<select id="mathFeature"></select></label><label>Hidden neuron<select id="mathNeuron"></select></label><label>Forward-pass model<select id="mathVariant"><option value="before">Observed / before update</option><option value="candidate">Candidate · diagnostic rescore</option><option value="active">Retained · diagnostic rescore</option></select></label></div>
   <div id="mathEquations" class="math-equations"><p class="math-empty">A measured input will reveal the live equations here.</p></div>
   <section id="mathLearning" class="math-learning" hidden><div class="math-subhead"><div><p class="math-kicker">CAPTURED INSIDE SGD</p><h3>One parameter. One real update.</h3></div><div class="math-learning-controls"><label>Captured training step<select id="mathEpoch"></select></label><label>Parameter<select id="mathParameter"><option value="w1">Input → hidden weight</option><option value="b1">Hidden bias</option><option value="w2">Hidden → output weight</option><option value="b2">Output bias</option></select></label></div></div><p id="mathSampling" class="math-caption"></p><div id="mathSGD"></div></section>
   <section id="mathComparison" hidden><div class="math-subhead"><div><p class="math-kicker">IDENTICAL FLOW · DIFFERENT WEIGHTS</p><h3>What changed? What stayed active?</h3></div></div><div id="mathModels" class="math-models"></div><p class="math-caption">Candidate and retained values rescore this same flow for comparison. They do not replace its original, pre-feedback prediction.</p><div id="mathGate" class="math-gate"></div></section>
   <details class="math-details"><summary>How to read this animation and verify its values</summary><p>Play, pause, arrows and the timeline control explanation playback only. The model has already computed the captured values. Smooth motion shows the order of operations, not measured execution time. Numbers are rounded for display; hover or export for full precision.</p><p>Select an input or neuron in the network, or use the labelled lists. The selected hidden neuron receives all 12 transformed inputs. Its activation is tanh of their weighted sum plus bias. The output uses all 24 hidden activations and a sigmoid. Glowing paths show mathematical dependencies, not captured packet travel or causal explanations.</p><p>For learning, the worker captures the first actual SGD step of each of three passes. Other training steps still run but are not individually stored. Full final candidate weights are retained for comparison. No training happens when you replay this explanation.</p><p>Up to eight recent candidate traces and the last streamed forward pass are stored locally. Single-flow captures stay in this tab until reload. Old sessions without traces need a new operation. Reset clears the trace history with the session.</p><p>Animation traces include submitted measurements and model snapshots. Their export is local, separate from AJRs, and is not independently notarized evidence.</p><button id="mathExport" disabled>Export this numerical trace</button></details>`;
  this.$=id=>root.querySelector('#'+id);
  for(let k=0;k<24;k++)this.$('mathNeuron').add(new Option('H'+(k+1),k));
  for(let j=0;j<12;j++)this.$('mathFeature').add(new Option(featureGuide[j][0],j));
  this.$('mathReduced').checked=matchMedia('(prefers-reduced-motion: reduce)').matches;
  this.$('mathReduced').onchange=()=>{this.pause();this.render()};
  this.$('mathHistory').onchange=()=>this.select(this.$('mathHistory').value,false);
  this.$('mathNeuron').onchange=()=>{this.pause();this.neuron=Number(this.$('mathNeuron').value);this.render()};
  this.$('mathFeature').onchange=()=>{this.pause();this.feature=Number(this.$('mathFeature').value);this.render()};
  this.$('mathVariant').onchange=()=>{this.pause();this.variant=this.$('mathVariant').value;this.render()};
  this.$('mathPlay').onclick=()=>this.timer?this.pause():this.play();
  this.$('mathReplay').onclick=()=>{this.move(0);this.play()};
  this.$('mathNext').onclick=()=>this.move(Math.min(this.lastStage(),this.stage+1));
  this.$('mathPrevious').onclick=()=>this.move(Math.max(0,this.stage-1));
  this.$('mathScrub').oninput=()=>this.move(Number(this.$('mathScrub').value));
  this.$('mathSpeed').onchange=()=>{if(this.timer){this.pause();this.play()}};
  this.$('mathEpoch').onchange=this.$('mathParameter').onchange=()=>{this.pause();this.render()};
  this.$('mathExport').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({schema:'drifttrust-math-trace-v1',scope:'Local numerical witness, not an independent attestation',capture:this.current},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='drifttrust-math-trace.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  root.addEventListener('click',e=>{if(e.target.closest('summary'))this.pause();const n=e.target.closest('[data-neuron],[data-feature],[data-math-step],[data-variant]');if(!n)return;this.pause();
   if(n.dataset.neuron!==undefined){this.neuron=Number(n.dataset.neuron);this.$('mathNeuron').value=this.neuron;this.render()}
   if(n.dataset.feature!==undefined){this.feature=Number(n.dataset.feature);this.$('mathFeature').value=this.feature;this.render()}
   if(n.dataset.mathStep!==undefined)this.move(Number(n.dataset.mathStep));
   if(n.dataset.variant){this.pause();this.variant=n.dataset.variant;this.render()}
  });
  root.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('g[data-neuron],g[data-feature]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}))}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)this.pause()});
  this.render();
 }
 configure(meta){this.meta=meta;this.render()}
 lastStage(){return this.current?.kind==='candidate'?6:3}
 pause(){clearTimeout(this.timer);this.timer=null;this.root.classList.remove('is-playing');this.$('mathPlay').textContent='▶ Play'}
 play(){if(!this.current)return;if(this.stage>=this.lastStage()){this.stage=0;this.applyStage()}this.pause();this.root.classList.add('is-playing');this.$('mathPlay').textContent='Ⅱ Pause';this.render();
  const advance=()=>{if(this.stage===4&&Number(this.$('mathEpoch').value)<2){this.$('mathEpoch').value=Number(this.$('mathEpoch').value)+1}else{this.stage++;this.applyStage();if(this.stage===4)this.$('mathEpoch').value=0}this.render();if(this.stage>=this.lastStage())this.pause();else this.timer=setTimeout(advance,1900/Number(this.$('mathSpeed').value))};
  this.timer=setTimeout(advance,1900/Number(this.$('mathSpeed').value));
 }
 applyStage(){this.variant=this.current?.kind==='candidate'?(this.stage===6?'active':this.stage===5?'candidate':'before'):'before'}
 move(stage){this.pause();this.stage=stage;this.applyStage();this.render()}
 clear(){this.pause();this.items=[];this.current=null;this.stage=0;this.variant='before';this.updateHistory();this.render()}
 updateHistory(){const select=this.$('mathHistory');select.replaceChildren();for(const item of [...this.items].reverse())select.add(new Option(item.title,item.id));if(!this.items.length)select.add(new Option('No calculation captured yet',''));select.disabled=!this.items.length;if(this.current)select.value=this.current.id}
 ingest(items,{autoplay=true}={}){if(!items?.length)return;const keep=new Map(this.items.map(i=>[i.id,i]));for(const item of items)keep.set(item.id,item);this.items=[...keep.values()].slice(-18);this.select(items.at(-1).id,autoplay)}
 select(id,autoplay=false){this.pause();this.current=this.items.find(i=>i.id===id);if(!this.current)return;this.stage=0;this.variant='before';this.updateHistory();this.$('mathEpoch').replaceChildren();for(const [i,s]of (this.current.steps??[]).entries())this.$('mathEpoch').add(new Option('Pass '+s.epoch+' · first training row',i));this.render();if(autoplay&&!this.$('mathReduced').checked)this.play()}
 candidate(attempt){const item=this.items.findLast(i=>i.record?.attempt===attempt);if(item){this.select(item.id);this.root.scrollIntoView({behavior:this.$('mathReduced').checked?'instant':'smooth',block:'start'});return true}return false}
 render(){
  const openDetails=[...this.root.querySelectorAll('details[open]')].map(d=>d.querySelector('summary').textContent);
  const focused=document.activeElement,focusKey=['data-neuron','data-feature','data-math-step','data-variant'].find(a=>this.root.contains(focused)&&focused.hasAttribute(a));
  const focusValue=focusKey?focused.getAttribute(focusKey):null;
  const t=this.current,isCandidate=t?.kind==='candidate',v=t?(this.variant==='candidate'?t.candidate:this.variant==='active'?t.active:t.forward):null;
  this.root.classList.toggle('motion-off',this.$('mathReduced').checked);this.root.dataset.phase=this.stage;this.root.dataset.captureKind=t?.kind??'empty';
  for(const id of ['mathReplay','mathPlay','mathNext','mathPrevious','mathScrub','mathExport','mathFeature','mathNeuron','mathParameter'])this.$(id).disabled=!t;
  this.$('mathNext').disabled=!t||this.stage>=this.lastStage();this.$('mathPrevious').disabled=!t||this.stage===0;
  this.$('mathVariant').disabled=!isCandidate;this.$('mathVariant').value=this.variant;
  this.$('mathStages').innerHTML=stages.slice(0,this.lastStage()+1).map((s,i)=>`<button data-math-step="${i}" ${!t?'disabled':''} aria-current="${this.stage===i?'step':'false'}"><span>${String(i+1).padStart(2,'0')}</span>${s}</button>`).join('');
  this.$('mathScrub').max=this.lastStage();this.$('mathScrub').value=this.stage;
  this.drawNetwork(v);
  this.$('mathLearning').hidden=!isCandidate;this.$('mathComparison').hidden=!isCandidate;
  if(!t){this.$('mathCapture').textContent='Start a session, then run Single flow or Dataset replay. Each animation uses an actual captured calculation.';this.$('mathStepNumber').textContent='READY';this.$('mathStepTitle').textContent='Your measurements become the next calculation.';this.$('mathNarration').textContent='Choose a flow below, then run inference. Or replay a labelled stream to reveal learning and the gate.';this.$('mathEquations').innerHTML='<p class="math-empty">Measured values and real model parameters will appear here after a calculation.</p>';return}
  this.$('mathCapture').textContent=`${t.title} · ${new Date(t.captured_at).toLocaleTimeString()} · Recorded computation, slowed for explanation. Playback does not run training.`;
  this.$('mathStepNumber').textContent=`STEP ${this.stage+1} / ${this.lastStage()+1}`;this.$('mathStepTitle').textContent=stages[this.stage];
  const descriptions=[`Input ${this.feature+1}: ${featureGuide[this.feature][0]}. The measured value passes through log1p and training normalization, then clipping to [−8, 8].`,
   `Follow H${this.neuron+1}. Its 12 incoming products are added to its bias, then tanh maps the sum to [−1, 1]. Click another neuron to inspect its real values.`,
   'All 24 hidden activations contribute to one output. Sigmoid maps its weighted sum to an attack score between 0 and 1.',
   `Subtract attack score ${fmt(v.p)} from 1, then multiply by 100. Trust is ${v.trust.toFixed(2)}. This uncalibrated score is not access permission.`,
   'The engine trained a separate candidate. Below are captured SGD updates from the first training row of each pass; intervening updates also ran.',
   'Rescore the identical probe flow with the old and fully trained candidate models. A changed output here comes from changed weights, because the input stays fixed.',
   isCandidate?(t.record.accepted?'The candidate was activated. '+(t.record.failed_checks.length?'Audit-only policy permits activation despite the recorded failed checks.':'Every configured check passed.'):'The candidate was discarded. The previous weights remain active; the candidate’s learning is not installed.'):''];
  this.$('mathNarration').textContent=descriptions[this.stage];this.equations(v);
  if(isCandidate){this.learning();this.comparison()}
  for(const detail of this.root.querySelectorAll('details'))if(openDetails.includes(detail.querySelector('summary').textContent))detail.open=true;
  if(focusKey)this.root.querySelector(`[${focusKey}="${focusValue}"]`)?.focus({preventScroll:true});
 }
 drawNetwork(v){
  const selected=this.neuron,j=this.feature,ins=Array.from({length:12},(_,i)=>({x:180,y:67+i*26})),hs=Array.from({length:24},(_,k)=>({x:480+Math.floor(k/12)*86,y:67+(k%12)*26})),out={x:817,y:210};
  let s=`<defs><filter id="neuronGlow" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="3"/></filter><linearGradient id="planeGlow" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#4adfdb" stop-opacity=".08"/><stop offset="1" stop-color="#4adfdb" stop-opacity="0"/></linearGradient></defs><path class="network-plane" d="M120 32 L211 16 L235 366 L144 391 Z"/><path class="network-plane" d="M424 30 L619 15 L644 369 L449 396 Z"/><path class="network-plane" d="M778 112 L853 100 L871 306 L796 319 Z"/><text class="layer-label" x="125" y="408">12 INPUTS</text><text class="layer-label" x="440" y="408">24 TANH NEURONS</text><text class="layer-label" x="770" y="355">SIGMOID</text>`;
  for(let k=0;k<24;k++){const h=hs[k];for(let i=0;i<12;i++){const p=ins[i],weight=v?.model.w1[i][k]??0;s+=`<path aria-hidden="true" class="network-edge ${k===selected?'selected-edge':''} ${k===selected&&this.stage===1?'signal':''}" d="M${p.x} ${p.y} C310 ${p.y},365 ${h.y},${h.x} ${h.y}" stroke="${weight<0?'#af9dff':'#55ded8'}" stroke-width="${k===selected?1+Math.min(2,Math.abs(weight)):0.5}" opacity="${k===selected?.6:.055}"><title>Input ${i+1} → H${k+1}: weight ${v?weight:'not captured'}</title></path>`}
   s+=`<path class="network-edge ${k===selected?'selected-edge':''} ${this.stage===2?'signal':''}" d="M${h.x} ${h.y} C685 ${h.y},733 210,817 210" stroke="${(v?.model.w2[k]??0)<0?'#af9dff':'#55ded8'}" stroke-width="${k===selected?2:0.7}" opacity="${k===selected?.8:.12}"><title>H${k+1} → output: weight ${v?.model.w2[k]??'not captured'}</title></path>`;
  }
  ins.forEach((p,i)=>{s+=`<g class="network-node" role="button" tabindex="0" aria-label="Inspect input ${i+1}: ${esc(featureGuide[i][0])}" data-feature="${i}"><title>${esc(featureGuide[i][0])}: raw ${v?.raw[i]??'—'}; transformed ${v?.x[i]??'—'}</title><text class="input-label" x="${p.x-25}" y="${p.y+4}" text-anchor="end">${['Duration','Forward pkts','Backward pkts','Packet rate','Down/up','SYN','RST','ACK','Payload μ','Payload σ','Fwd window','Bwd window'][i]}</text><circle cx="${p.x}" cy="${p.y}" r="${i===j?8:5}" fill="${(v?.x[i]??0)<0?'#af9dff':'#55ded8'}"/><circle class="node-ring" cx="${p.x}" cy="${p.y}" r="${i===j?13:9}"/></g>`});
  hs.forEach((p,k)=>{const a=v?.hidden[k]??0;s+=`<g class="network-node ${selected===k?'selected-node':''}" role="button" tabindex="0" aria-label="Inspect hidden neuron H${k+1}" data-neuron="${k}"><title>H${k+1}: activation ${v? a:'not captured'}</title><circle cx="${p.x}" cy="${p.y}" r="12" fill="${a<0?'#af9dff':'#55ded8'}" opacity="${v?.hidden? .12+.45*Math.abs(a):.12}" filter="url(#neuronGlow)"/><circle cx="${p.x}" cy="${p.y}" r="${k===selected?8:5}" fill="${a<0?'#af9dff':'#55ded8'}" opacity="${v?.hidden?.length?.35+.65*Math.abs(a):.35}"/><circle class="node-ring" cx="${p.x}" cy="${p.y}" r="11"/><text class="neuron-label" x="${p.x+15}" y="${p.y+4}">H${k+1}</text></g>`});
  s+=`<circle cx="817" cy="210" r="34" fill="#55ded8" opacity=".12" filter="url(#neuronGlow)"/><circle cx="817" cy="210" r="25" fill="#133b49" stroke="#55ded8"/><text x="817" y="216" text-anchor="middle" class="output-symbol">σ</text><text x="817" y="268" text-anchor="middle" class="output-value">${v?fmt(v.p):'—'}</text><path class="network-edge ${this.stage===3?'signal':''}" d="M842 210 L920 210" stroke="#55ded8" stroke-width="2"/><rect x="923" y="164" width="163" height="98" rx="16" fill="#102c38" stroke="#315762"/><text class="layer-label" x="1004" y="188" text-anchor="middle">TRUST / 100</text><text class="trust-network-value" x="1004" y="236" text-anchor="middle">${v?v.trust.toFixed(1):'—'}</text>`;
  this.$('mathNetwork').innerHTML=s;
 }
 equations(v){const j=this.feature,k=this.neuron,terms=v.hidden_terms[k],weighted=terms.reduce((a,b)=>a+b,0),ot=v.output_terms.reduce((a,b)=>a+b,0);
  this.$('mathEquations').innerHTML=`<div class="equation-section ${this.stage===0?'equation-focus':''}"><div class="equation-heading"><span>01</span><h3>Prepare ${esc(featureGuide[j][0])}</h3></div><div class="boxed-equation">${box('Measured x',v.raw[j])}<b>→ (</b>${box('log(1 + x)',v.log[j])}<b>−</b>${box('Training mean',v.mean[j])}<b>) ÷</b>${box('Training SD',v.scale[j])}<b>→</b>${box('Transformed x',v.x[j],'box-answer')}</div><p class="math-caption">(log(1 + x) − mean) ÷ SD = ${fmt(v.standardized[j])}; clip to [−8, 8] → ${fmt(v.x[j])}. ${v.standardized[j]!==v.x[j]?'Clipping was applied.':'No clipping was needed.'}</p></div>
   <div class="equation-section ${this.stage===1?'equation-focus':''}"><div class="equation-heading"><span>02</span><h3>Inside H${k+1}</h3></div><div class="boxed-equation">${box('Weight w['+(j+1)+','+(k+1)+']',v.model.w1[j][k])}<b>×</b>${box('Transformed input',v.x[j])}<b>=</b>${box('One of 12 products',terms[j],'box-answer')}</div><div class="boxed-equation">${box('Sum of all 12 products',weighted)}<b>+</b>${box('Hidden bias',v.model.b1[k])}<b>→ tanh →</b>${box('Hidden activation',v.hidden[k],'box-answer')}</div><details class="math-details"><summary>Expand all 12 incoming terms and their sum</summary><div class="math-table-wrap"><table><thead><tr><th>Input</th><th>Transformed x</th><th>Weight</th><th>Product</th></tr></thead><tbody>${terms.map((p,i)=>`<tr class="${i===j?'selected-term':''}"><td>${esc(featureGuide[i][0])}</td><td>${fmt(v.x[i])}</td><td>${fmt(v.model.w1[i][k])}</td><td>${fmt(p)}</td></tr>`).join('')}</tbody></table></div><p>Weighted sum ${fmt(weighted)} + bias ${fmt(v.model.b1[k])} = ${fmt(v.hidden_sums[k])}; tanh = ${fmt(v.hidden[k])}.</p></details></div>
   <div class="equation-section ${this.stage===2?'equation-focus':''}"><div class="equation-heading"><span>03</span><h3>From 24 activations to an attack score</h3></div><div class="boxed-equation">${box('Sum of 24 output products',ot)}<b>+</b>${box('Output bias',v.model.b2)}<b>→ sigmoid →</b>${box('Attack score',v.p,'box-answer')}</div><p class="math-caption">Output logit = ${fmt(v.logit)}. Sigmoid(z) = 1 ÷ (1 + exp(−z)), evaluated with the engine’s numerically stable form.</p><details class="math-details"><summary>Expand all 24 output terms</summary><div class="math-table-wrap"><table><thead><tr><th>Neuron</th><th>Activation</th><th>Output weight</th><th>Product</th></tr></thead><tbody>${v.hidden.map((h,i)=>`<tr><td>H${i+1}</td><td>${fmt(h)}</td><td>${fmt(v.model.w2[i])}</td><td>${fmt(v.output_terms[i])}</td></tr>`).join('')}</tbody></table></div></details></div>
   <div class="equation-section trust-equation ${this.stage===3?'equation-focus':''}"><div class="equation-heading"><span>04</span><h3>A score, translated into trust</h3></div><div class="boxed-equation"><b>100 × ( 1 −</b><div id="mathAttack">${box('Attack score',v.p)}</div><b>) =</b><div id="mathTrust">${box('Trust / 100',v.trust,'box-answer')}</div></div><p id="mathTrustArithmetic">1 − ${fmt(v.p)} = ${fmt(v.complement)}. Then 100 × ${fmt(v.complement)} = ${v.trust.toFixed(6)}.</p><p id="mathClassification" class="math-caption">${this.current.label===0||this.current.label===1?`Known/supplied label: ${this.current.label?'attack':'benign'}. ${Number(v.p>=.5)===this.current.label?'Correct classification for this input.':this.current.label?'Missed attack: this high trust score is wrong.':'False alarm on a benign flow.'}`:'Correctness unknown: no validated label accompanies this input.'}</p></div>`;
 }
 learning(){const t=this.current,step=t.steps[Number(this.$('mathEpoch').value)||0],kind=this.$('mathParameter').value,k=this.neuron,j=this.feature,r=parameterStep(step,kind,j,k);
  this.$('mathSampling').textContent=`Pass ${step.epoch} of 3 · training row 1 of ${t.training_size} · record ${step.record_id}. Only the first update of each pass is captured; these three samples are not consecutive training steps. These training inputs differ from the displayed probe flow.`;
  this.$('mathSGD').innerHTML=`<p>Selected parameter: <b>${kind==='w1'?`input ${j+1} → H${k+1} weight`:kind==='b1'?`H${k+1} bias`:kind==='w2'?`H${k+1} → output weight`:'output bias'}</b>.</p><div class="boxed-equation">${box('Old parameter',r.before)}<b>−</b>${box('Learning rate',r.lr)}<b>×</b>${box('Update term',r.gradient)}<b>=</b>${box('New parameter',r.after,'box-candidate')}</div><p id="mathDelta">Actual change: ${r.delta>=0?'+':''}${r.delta.toPrecision(8)}. Update term = ${esc(r.expression)}.</p><details class="math-details"><summary>Trace the gradient back to its label and prediction</summary><div class="boxed-equation">${box('Training prediction p',step.p)}<b>−</b>${box('Feedback label y',step.y)}<b>=</b>${box('Output error',step.error)}</div><p>For H${k+1}: hidden gradient = error × old output weight × (1 − activation²) = ${fmt(step.error)} × ${fmt(step.before.w2[k])} × (1 − ${fmt(step.hidden[k])}²) = ${fmt(step.dh[k])}.</p><p>Selected training input: ${fmt(step.x[j])}. L2 coefficient: ${step.l2}; it applies to weights only. New parameter = ${r.before} − ${r.lr} × ${r.gradient} = ${r.after}.</p></details>`;
 }
 comparison(){const t=this.current,r=t.record,ex=decisionExplanation(r,t.config,t.mode);
  this.$('mathModels').innerHTML=[['before','Before update',t.forward,r.model_before_sha256],['candidate','Trained candidate',t.candidate,r.candidate_sha256],['active',r.accepted?'Candidate activated':'Previous model retained',t.active,r.active_model_sha256]].map(([key,label,v,hash])=>`<button class="math-model-card ${this.variant===key?'model-selected':''} ${key==='candidate'?'candidate-card':''}" data-variant="${key}" aria-pressed="${this.variant===key}"><span>${label}</span><strong>${v.trust.toFixed(2)}<small> trust / 100</small></strong><span>Attack ${v.p.toFixed(6)}</span><code title="${hash}">${hash.slice(0,10)}…${hash.slice(-6)}</code></button>`).join('');
  const status=r.accepted?(r.failed_checks.length?'ACTIVATED WITH FLAGS':'CANDIDATE ACTIVATED'):'CANDIDATE DISCARDED';
  this.$('mathGate').className='math-gate '+(r.accepted?(r.failed_checks.length?'gate-flags':'gate-accepted'):'gate-rejected');
  this.$('mathGate').innerHTML=`<div class="gate-verdict"><span aria-hidden="true">${r.accepted?'✓':'×'}</span><div><p class="math-kicker">POLICY OUTCOME · CANDIDATE ${r.attempt}</p><h3>${status}</h3><p>${esc(ex.headline)} ${esc(ex.policy)}</p></div></div><div class="math-checks">${ex.checks.map(c=>`<div><b>${c.pass?'✓ PASS':'× FAIL'} · ${esc(c.name)}</b><p>${esc(c.before)} → ${esc(c.after)}</p><p>${esc(c.limit)}</p><small>${esc(c.why)}</small></div>`).join('')}</div><p class="math-caption">The gate governs model updates, not people or network access. Candidate traces are historical snapshots; later updates may have changed the current session model.</p>`;
 }
}
