import {metricGuide,modelGuide,featureGuide,figureGuide} from './explanations.mjs';
const $=id=>document.getElementById(id),fmt=x=>x?x.mean.toFixed(3)+' ± '+x.sd.toFixed(3):'—';
const keys=['Logistic regression','Random forest','static','ungoverned','monitor_only','governed','no_replay','no_attribution'];
const data=await fetch('assets/research/results.json').then(r=>{if(!r.ok)throw Error();return r.json()}).catch(()=>null);
for(const [key,[label]]of Object.entries(metricGuide)){const o=document.createElement('option');o.value=key;o.textContent=label;$('explainMetric').append(o)}
function explain(){if(!data)return;const key=$('explainModel').value,metric=$('explainMetric').value,r=data.summary.find(r=>r.protocol===$('protocol').value&&r.model===key);if(!r)return;const [label,meaning,formula]=metricGuide[metric],v=r[metric];const direction=metric==='benign_false_alarm_rate'?'Lower is better.':metric==='attempts'?'More attempts do not necessarily mean better performance.':'Higher is better.';
 let interpretation=metric==='attack_recall'?`Across these splits, the average attack detection fraction is ${(100*v.mean).toFixed(2)}%. Its complement is ${(100*(1-v.mean)).toFixed(2)}% missed attacks.`:metric==='benign_false_alarm_rate'?`Across these splits, an average ${(100*v.mean).toFixed(2)}% of benign flows are wrongly flagged.`:metric==='attempts'?`Mean ${v.mean.toFixed(2)} attempts per run includes both activated and discarded candidate models. This is not the number of attack flows.`:metric==='balanced_accuracy'?`The average of the two class recalls is ${(100*v.mean).toFixed(2)}%; it is not weighted by their different record counts.`:`F1 is ${v.mean.toFixed(4)} on a 0–1 scale. Do not read this as ${(100*v.mean).toFixed(2)}% of all flows being correct.`;
 $('metricMeaning').replaceChildren();for(const t of [`${r.name} · ${label}: ${v.mean.toFixed(4)} ± ${v.sd.toFixed(4)}.`,modelGuide[key],meaning+' '+direction,'Calculation: '+formula+'.',interpretation,'The ± value is sample standard deviation over five seeded splits. Changing the protocol selects a different measured experiment; it does not rerun models in this page.']){const p=document.createElement('p');p.textContent=t;$('metricMeaning').append(p)}}
function render(){if(!data){$('resultHighlights').textContent='Results unavailable. Check your connection or download the CSV below.';return}const map=Object.fromEntries(data.summary.filter(r=>r.protocol===$('protocol').value).map(r=>[r.model,r]));const selected=$('explainModel').value||'governed';$('explainModel').replaceChildren();$('resultsBody').replaceChildren();
 for(const key of keys){const r=map[key],o=document.createElement('option');o.value=key;o.textContent=r.name;$('explainModel').append(o);const tr=document.createElement('tr');if(['monitor_only','governed'].includes(key))tr.className='highlight';const name=document.createElement('td'),b=document.createElement('button');b.className='metric-button';b.textContent=r.name;b.title='Explain '+r.name;b.onclick=()=>{$('explainModel').value=key;explain();$('metricMeaning').scrollIntoView({block:'nearest'})};name.append(b);tr.append(name);for(const metric of ['attack_f1','balanced_accuracy','attack_recall','benign_false_alarm_rate','attempts']){const td=document.createElement('td');td.textContent=metric==='attempts'?r.attempts.mean.toFixed(1):fmt(r[metric]);tr.append(td)}$('resultsBody').append(tr)}$('explainModel').value=selected;$('resultHighlights').replaceChildren();for(const [key,label]of [['static','Frozen model · attack F1'],['monitor_only','Audit-only adaptation · attack F1'],['governed','Gated adaptation · attack F1']]){const d=document.createElement('div');d.className='metric';const b=document.createElement('b');b.textContent=map[key].attack_f1.mean.toFixed(3);const span=document.createElement('span');span.textContent=label;d.append(b,span);$('resultHighlights').append(d)}explain()}
$('protocol').onchange=render;$('explainModel').onchange=explain;$('explainMetric').onchange=explain;render();

for(const [id,title,short,long]of figureGuide){const c=document.createElement('article');c.className='figure-card';const img=document.createElement('img');img.src='assets/research/figures/'+id+'.svg';img.alt=title+': '+short;img.loading='lazy';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=short;const details=document.createElement('details'),summary=document.createElement('summary'),ex=document.createElement('p');summary.textContent='Explain this entire figure';ex.textContent=long;details.append(summary,ex);const links=document.createElement('div');links.className='figure-links';for(const ext of ['pdf','svg','png']){const a=document.createElement('a');a.href='assets/research/figures/'+id+'.'+ext;a.textContent=ext.toUpperCase();a.title='Download '+title+' as '+ext.toUpperCase();a.download=id+'.'+ext;links.append(a)}c.append(img,h,p,details,links);$('figureGrid').append(c)}
for(const [title,units,meaning]of featureGuide){const p=document.createElement('p'),b=document.createElement('b');b.textContent=title+' ('+units+'): ';p.append(b,document.createTextNode(meaning));$('indexFeatureGuide').append(p)}
