// Standalone browser acceptance check. Use the same runtime overrides as browser-pages.cjs.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');let browser;
(async()=>{
 const base=process.argv[2]||'http://localhost:8788/drifttrust_audit/';fs.mkdirSync('.local',{recursive:true});
 browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce',acceptDownloads:true});
 const page=await context.newPage();page.setDefaultTimeout(30000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const ready=()=>page.waitForFunction(()=>document.querySelector('#serviceText')?.textContent.includes('Real model ready'));
 const settled=()=>page.waitForFunction(()=>!document.getElementById('newSession').disabled);
 const seen=n=>page.waitForFunction(n=>document.getElementById('seen').textContent===String(n),n);
 const phase=n=>page.waitForFunction(n=>document.getElementById('mathTheatre').dataset.phase===String(n),n);
 const text=id=>page.locator('#'+id).innerText();
 const number=async selector=>Number(await page.locator(selector).getAttribute('data-value'));
 const selectCandidate=async attempt=>{await page.waitForFunction(n=>[...document.querySelectorAll('#mathHistory option')].some(o=>o.textContent.startsWith('Candidate #'+n+' ')),attempt);const value=await page.locator('#mathHistory option').evaluateAll((os,n)=>os.find(o=>o.textContent.startsWith('Candidate #'+n+' '))?.value,attempt);assert.ok(value);await page.locator('#mathHistory').selectOption(value)};
 const exportTrace=async name=>{const detail=page.locator('#mathExport').locator('..');if(!await detail.evaluate(d=>d.open))await detail.locator('summary').click();const event=page.waitForEvent('download');await page.locator('#mathExport').click();await(await event).saveAs('.local/'+name+'.json');return JSON.parse(fs.readFileSync('.local/'+name+'.json'))};
 await page.goto(base+'lab.html');await ready();assert.ok(await page.locator('#mathPlay').isDisabled());assert.ok(await page.locator('#mathReduced').isChecked());
 await page.locator('#mode').selectOption('governed');await page.locator('#newSession').click();await settled();await page.locator('#mathRun').click();await settled();await phase(0);
 assert.equal(await text('seen'),'0');assert.ok((await text('mathClassification')).includes('Correct classification'));
 const p=await number('#mathAttack output'),trust=await number('#mathTrust output');assert.equal(trust,100*(1-p));assert.equal(parseFloat(await text('scoreValue')),Number(trust.toFixed(1)));
 assert.equal(await page.locator('#mathNetwork g[data-neuron]').count(),24);assert.equal(await page.locator('#mathNetwork g[data-feature]').count(),12);
 const inputs=page.locator('#mathEquations details').nth(0),outputs=page.locator('#mathEquations details').nth(1);
 await inputs.locator('summary').click();assert.equal(await inputs.locator('tbody tr').count(),12);await outputs.locator('summary').click();assert.equal(await outputs.locator('tbody tr').count(),24);
 await page.locator('#mathFeature').selectOption('11');await page.locator('#mathNeuron').selectOption('23');assert.ok(await inputs.evaluate(d=>d.open));
 const node=page.locator('#mathNetwork g[data-neuron="22"]');await node.focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#mathNeuron').inputValue(),'22');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('data-neuron')),'22');
 await page.locator('#tab-replay').click();await page.locator('.math-input-link').click();assert.ok(await page.locator('#single').isVisible());
 const good=await page.locator('#f0').inputValue(),captureId=await page.locator('#mathHistory').inputValue();await page.locator('#f0').fill('-1');await page.locator('#tab-replay').click();await page.locator('#mathRun').click();assert.ok(await page.locator('#single').isVisible());assert.equal(await page.locator('#mathHistory').inputValue(),captureId);await page.locator('#f0').fill(good);
 const revision=await text('sessionMeta');await page.locator('#mathNext').click();await phase(1);await page.locator('#mathPrevious').click();await phase(0);await page.locator('#mathScrub').fill('3');await phase(3);
 await page.locator('#mathSpeed').selectOption('2');await page.locator('#mathReplay').click();await phase(0);await phase(1);await page.locator('#mathPlay').click();assert.equal(await text('mathPlay'),'▶ Play');assert.equal(await text('sessionMeta'),revision);
 const inference=await exportTrace('math-inference');assert.equal(inference.schema,'drifttrust-math-trace-v1');assert.equal(inference.capture.forward.p,p);assert.equal(inference.capture.forward.model.w1.length,12);
 await page.locator('#mathTheatre').scrollIntoViewIfNeeded();await page.evaluate(()=>document.getElementById('mathTheatre').scrollIntoView({block:'start'}));await page.screenshot({path:'.local/math-network-viewport.png'});
 await page.locator('#tab-replay').click();await page.locator('#replayAll').click();await seen(1280);await settled();await selectCandidate(7);
 assert.ok((await text('mathGate')).includes('CANDIDATE DISCARDED'));assert.equal(await page.locator('#mathGate .math-checks > div').count(),4);assert.equal(await page.locator('#mathEpoch option').count(),3);
 const trace=await exportTrace('math-candidate'),c=trace.capture;assert.equal(c.record.accepted,false);assert.deepEqual(c.active.model,c.forward.model);assert.notDeepEqual(c.active.model,c.candidate.model);assert.equal(c.steps.length,3);
 await page.locator('#mathVariant').selectOption('candidate');assert.equal(await number('#mathTrust output'),c.candidate.trust);await page.locator('#mathVariant').selectOption('active');assert.equal(await number('#mathTrust output'),c.forward.trust);
 for(const kind of ['w1','b1','w2','b2']){await page.locator('#mathParameter').selectOption(kind);for(const index of ['0','1','2']){await page.locator('#mathEpoch').selectOption(index);const s=c.steps[Number(index)],boxes=await page.locator('#mathSGD > .boxed-equation output').evaluateAll(os=>os.map(o=>Number(o.dataset.value)));assert.ok(Math.abs(boxes[0]-boxes[1]*boxes[2]-boxes[3])<1e-12);assert.equal(boxes[1],s.learning_rate)}}
 await page.locator('#mathReduced').uncheck();await page.locator('#mathScrub').fill('3');await page.locator('#mathPlay').click();await phase(4);await page.waitForFunction(()=>document.querySelector('#mathEpoch').value==='0');await page.waitForFunction(()=>document.querySelector('#mathEpoch').value==='1');await page.waitForFunction(()=>document.querySelector('#mathEpoch').value==='2');await phase(6);assert.equal(await page.locator('#mathVariant').inputValue(),'active');assert.equal(await text('mathPlay'),'▶ Play');
 const finalRevision=await text('sessionMeta');await page.locator('#mathReduced').check();assert.ok(await page.locator('#mathNext').isDisabled());await page.screenshot({path:'.local/math-gate-desktop.png',fullPage:true});await page.evaluate(()=>document.getElementById('mathLearning').scrollIntoView({block:'start'}));await page.screenshot({path:'.local/math-learning-viewport.png'});
 for(const width of [1440,820,390]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#mathTheatre').screenshot({path:`.local/math-${width}.png`})}
 await page.setViewportSize({width:1440,height:1100});await page.addStyleTag({content:'html {font-size: 200% !important}'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.reload();await ready();await seen(1280);await selectCandidate(7);assert.equal(await text('sessionMeta'),finalRevision);assert.ok((await text('mathGate')).includes('CANDIDATE DISCARDED'));assert.equal(await text('mathPlay'),'▶ Play');
 await page.locator('#mathReduced').check();await page.locator('#mode').selectOption('monitor_only');await page.locator('#newSession').click();await settled();assert.equal(await page.locator('#mathHistory option').count(),1);assert.ok(await page.locator('#mathPlay').isDisabled());
 await page.locator('#tab-replay').click();await page.locator('#replayAll').click();await seen(1280);await settled();assert.equal(await text('accepted'),'5');
 const values=await page.locator('#mathHistory option').evaluateAll(os=>os.filter(o=>o.textContent.startsWith('Candidate #')).map(o=>o.value));let flags=false;for(const v of values){await page.locator('#mathHistory').selectOption(v);if((await text('mathGate')).includes('ACTIVATED WITH FLAGS')){flags=true;break}}assert.ok(flags,'audit-only failed checks must be shown as activation with flags');
 assert.deepEqual(errors,[]);const result={base,checked_at_utc:new Date().toISOString(),passed:true,checks:['actual single-flow arithmetic and 12–24–1 network','all input/output terms','keyboard neuron inspection and focus retention','expanded equations survive re-render','play/pause/replay/arrows/timeline/speed','three captured SGD steps play in order','all four parameter types reconstruct updates','before/candidate/retained numerical comparison','rejected candidate retains exact previous weights','audit-only activation explicitly shows failed checks','full-precision numerical trace export','playback does not change session revision','trace persistence and reset','system and manual reduced motion','1440/820/390 layouts and 200% text sizing'],runtime_errors:errors};fs.writeFileSync('.local/math-verification.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(async error=>{console.error(error);if(browser)await browser.close();process.exit(1)});
