const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');let browser;
(async()=>{
 fs.mkdirSync('.local',{recursive:true});
 const base=process.argv[2]||'http://localhost:8788/drifttrust_audit/';browser=await chromium.launch({...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{}),headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(25000);const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST'||r.url().includes('/api/')||r.url().includes('chatgpt.site'))requests.push({method:r.method(),url:r.url()})});
 const contains=async(id,t)=>assert.ok((await page.locator('#'+id).innerText()).includes(t),`${id} must include ${t}`);
 const ready=async()=>page.waitForFunction(()=>document.querySelector('#serviceText')?.textContent.includes('Real model ready'));
 const count=async(id,n)=>page.waitForFunction(({id,n})=>document.getElementById(id).textContent===String(n),{id,n});
 const settled=async()=>page.waitForFunction(()=>!document.getElementById('newSession').disabled);
 await page.goto(base);await page.waitForFunction(()=>document.querySelectorAll('#resultsBody tr').length===8);assert.equal(await page.locator('.figure-card').count(),9);await page.locator('#explainMetric').selectOption('benign_false_alarm_rate');await contains('metricMeaning','benign flows');const before=await page.locator('#metricMeaning').innerText();await page.locator('#protocol').selectOption('stationary');assert.notEqual(await page.locator('#metricMeaning').innerText(),before);await page.locator('.figure-card details').first().locator('summary').click();await page.screenshot({path:'.local/pages-evidence.png',fullPage:true});
 await page.goto(base+'lab.html');await ready();assert.equal(await page.locator('.feature-cell').count(),12);await page.locator('#newSession').click();await settled();await page.locator('#infer').click();await settled();await contains('scoreMeaning','correct classification');await contains('seen','0');const options=await page.locator('#example option').allTextContents();const arp=options.findIndex(x=>x.startsWith('ARP_poisioning'));await page.locator('#example').selectOption(String(arp));await page.locator('#infer').click();await settled();await contains('scoreMeaning','missed attack');await contains('scoreValue','80.5');assert.equal(await page.locator('.explanation-detail').count(),12);await page.locator('#f3').fill('0');await contains('exampleNote','EDITED INPUT');await page.locator('#infer').click();await settled();await contains('scoreMeaning','correctness is unknown');await page.locator('[data-stage="3"]').click();await contains('stageHelp','Candidate');
 await page.locator('#tab-replay').click();await page.locator('#replayBatch').click();await count('seen',128);await settled();await contains('detectorMeaning','128');await page.evaluate(()=>{document.getElementById('replayAll').click();document.getElementById('stopReplay').click()});await count('seen',256);await settled();assert.equal(await page.locator('#seen').innerText(),'256');await page.locator('#replayAll').click();await count('seen',1280);await settled();await contains('attempts','5');await contains('accepted','5');await page.locator('#verifyAudit').click();await settled();await contains('verifyState','Verified 5');const dl=page.waitForEvent('download');await page.locator('#exportAudit').click();const download=await dl;await download.saveAs('.local/browser-audit.json');await settled();assert.equal(JSON.parse(fs.readFileSync('.local/browser-audit.json')).records.length,5);
 await page.reload();await ready();await count('seen',1280);assert.equal(await page.locator('#streamChart polyline').count(),1);await contains('scoreNote','Restored');await page.locator('#pointPicker').fill('0');await contains('pointMeaning','Flow position 769');
 const other=await browser.newContext();const p2=await other.newPage();await p2.goto(base+'lab.html');await p2.waitForFunction(()=>document.querySelector('#serviceText')?.textContent.includes('Real model ready'));assert.equal(await p2.locator('#seen').innerText(),'0');await other.close();
 await page.locator('#mode').selectOption('governed');await contains('policyHelp','NEXT');await page.locator('#newSession').click();await count('seen',0);await settled();await page.locator('#tab-replay').click();await page.locator('#replayAll').click();await count('seen',1280);await settled();await contains('attempts','7');await contains('accepted','4');await contains('rejected','3');await page.locator('.audit-record > summary').first().click();await contains('auditRecords','0.07899');await contains('auditRecords','0.11328');await contains('auditRecords','0.19226');await page.locator('#auditFilter').selectOption('rejected');assert.equal(await page.locator('.audit-record').count(),3);await page.locator('#auditFilter').selectOption('all');await page.locator('.audit-record > summary').first().click();await page.screenshot({path:'.local/pages-gated-audit.png',fullPage:true});
 await page.locator('#newSession').click();await count('seen',0);await settled();await page.locator('#tab-upload').click();const bundle=JSON.parse(fs.readFileSync('assets/research/model.json')),replay=JSON.parse(fs.readFileSync('assets/research/replay.json')).rows;const csv=bundle.features.concat('label').join(',')+'\n'+replay.slice(0,256).map(r=>r.x.concat('').join(',')).join('\n');await page.locator('#csvFile').setInputFiles({name:'unlabelled-measured.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await page.locator('#submitCSV').click();await count('seen',256);await settled();await contains('attempts','0');await contains('detectorMeaning','no feedback labels');
 const labelled=bundle.features.concat('label').join(',')+'\n'+replay.slice(0,256).map(r=>r.x.concat(r.y).join(',')).join('\n');await page.locator('#csvFile').setInputFiles({name:'labelled-measured.csv',mimeType:'text/csv',buffer:Buffer.from(labelled)});await page.locator('#submitCSV').click();await count('seen',512);await settled();const revision=await page.locator('#sessionMeta').innerText();await page.locator('#csvFile').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from('bad,label\n1,3')});await page.locator('#submitCSV').click();await settled();assert.equal(await page.locator('#error').isVisible(),true);assert.equal(await page.locator('#sessionMeta').innerText(),revision);
 for(const width of [1440,820,390]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`.local/pages-lab-${width}.png`,fullPage:true})}
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 const result={base,checked_at_utc:new Date().toISOString(),passed:true,execution:'browser Web Worker + IndexedDB',audit_only:{flows:1280,candidates:5,activated:5,discarded:0},gated:{flows:1280,candidates:7,activated:4,discarded:3},checks:['dynamic metric explanations','nine figure explanations','12 feature definitions','actual initial model outputs','edited-input correctness notice','all 12 contributions','detector explanations','pause after current replay request','full replay in both policies','numerical rejection explanation','local chart persistence','browser-profile isolation','audit chain verification and export','unlabelled and labelled CSV','invalid CSV atomic rejection','responsive overflow'],api_or_form_posts:requests.length,runtime_errors:errors};fs.writeFileSync('.local/pages-verification.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1)});
